name: Build and Publish to Github Container Registry

on:
  push:
    branches: [ master ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build TypeScript
        run: npm run build
      - name: Run tests
        run: npm run test
      - name: Login onto ghcr
        run: |
          echo "${{ secrets.MALDORNE_BOT_GHCR_TOKEN }}" | docker login ghcr.io --username maldorne-bot --password-stdin
      - name: Build image
        run: |
          docker build --no-cache . -t ghcr.io/maldorne/mud-web-proxy:latest
      - name: Publish image
        run: |
          docker push ghcr.io/maldorne/mud-web-proxy:latest
